import Head from 'next/head'

import Banner from '../components/Banner'
import Header from '../components/Header'
import SmallCard from '../components/SmallCard'
import styles from '../styles/Home.module.css'

export default function Home({exploreData}) {
  return (
    <div className="">
      <Head>
        <title>AirBnB Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      {/* banner (hero) */}
      <Banner />
      {/* main */}
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>

          {/* get data from endpoint */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(({img, location, distance}) => (
              <SmallCard
                key={img}
                img={img}
                location={location}
                distance={distance}
              />
            ))}
          </div>
        </section>
      </main>
    </div>
  )
}

// https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props#getserversideprops
export async function getStaticProps() {
  const res = await fetch(`https://links.papareact.com/pyp`)
  const exploreData = await res.json()
  return {props: {exploreData}}
}
