import Head from 'next/head'

import Banner from '../components/Banner'
import Header from '../components/Header'
import LargeCard from '../components/LargeCard'
import MediumCard from '../components/MediumCard'
import SmallCard from '../components/SmallCard'
import styles from '../styles/Home.module.css'

export default function Home({exploreData, cardsData}) {
  return (
    <div className="">
      <Head>
        <title>AirBnB Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      {/* banner (hero) */}
      <Banner />
      {/* main */}
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>

          {/* get data from endpoint */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(({img, location, distance}) => (
              <SmallCard
                key={img}
                img={img}
                location={location}
                distance={distance}
              />
            ))}
          </div>
        </section>
        <section className="pt-6">
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {cardsData?.map(({img, title}) => (
              <MediumCard key={img} img={img} title={title} />
            ))}
          </div>
        </section>
        <LargeCard
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoors"
          description="Wishlists curated by AirBnB"
          buttonText="Get Inspired"
        />
      </main>
    </div>
  )
}

// https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props#getserversideprops
export async function getStaticProps() {
  let res = await fetch(`https://links.papareact.com/pyp`)
  const exploreData = await res.json()

  res = await fetch(`https://links.papareact.com/zp1`)
  const cardsData = await res.json()
  return {props: {exploreData, cardsData}}
}
